# Generated by Django 2.2.3 on 2019-07-13 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190707_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='lastmodified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploadedby',
            field=models.TextField(default='vincent'),
            preserve_default=False,
        ),
    ]
