# Generated by Django 2.2.3 on 2019-07-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190713_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='lastmodified',
            new_name='lastuploadtime',
        ),
    ]
