# Generated by Django 2.2.3 on 2019-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190713_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.Field(),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedby',
            field=models.Field(),
        ),
    ]
